apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: mongodb
  labels:
    team: platform
    tier: database
    app: mongodb
    role: single-node

spec:
  revisionHistoryLimit: 1

  strategy:
    type: Recreate

  template:
    metadata:
      name: mongodb
      labels:
        team: platform
        tier: database
        app: mongodb
        role: single-node
    spec:
      containers:
      - name: mongodb
        imagePullPolicy: Always
        image: mongo:3.3

        ports:
        - containerPort: 27017


        resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
