sudo: required

language: go

services:
  - docker

script:
- docker build -t kubernetes-deployment --no-cache --target builder .
- >
  docker run
  --name kubernetes-deployment
  --entrypoint "sh"
  kubernetes-deployment
  -euxc "make xc"
- docker cp -L kubernetes-deployment:/src/dist ./releases
- ls -l *

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    repo: rebuy-de/kubernetes-deployment
    tags: true

