[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v15.0.0"

[[constraint]]
  name = "github.com/gregjones/httpcache"
  branch = "master"

[[constraint]]
  name = "github.com/imdario/mergo"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rebuy-de/rebuy-go-sdk"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "gopkg.in/alexcesaro/statsd.v2"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/gemnasium/logrus-graylog-hook.v2"
  version = "2.0.6"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.6"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.6"

[[constraint]]
  branch = "master"
  name = "github.com/benbjohnson/clock"

[[constraint]]
  name = "github.com/google/go-jsonnet"
  version = "^0.10.0"
