defaults:
  owner: rebuy-de
  path: k8s
  context: prod
  variables:
    stage: unknown

contexts:
  prod:
    variables:
      stage: production
  test:
    variables:
      stage: testing

services:
- repo: foobar
- repo: repo-no-exist
- name: no-files
  repo: foobar
  path: does-not-exist
- name: invalid-file
  repo: foobar
  path: invalid
