defaults:
  owner: rebuy-de
  path: k8s
  ref: master
  variables:
    stage: unknown
  interceptors:
    preStopSleep:
      enabled: null
      options:
        seconds: 3
    removeResourceSpecs:
      enabled: null
    removeOldJob:
      enabled: null
    waiter:
      enabled: null
    annotater:
      enabled: null
    grafannotator:
      enabled: null
      options:
        targetURL: ""
        username: ""
        password: ""
    injector:
      enabled: null
    ghStatusChecker:
      enabled: null
      options:
        targetUrlRegex: .*
        contextRegex: .*
        initialDelay: 20s
        pullInterval: 10s
        notificationInterval: 3m0s
services:
- name: foobar
  aliases:
  - fbr
  owner: rebuy-de
  repo: foobar
  path: k8s/
  ref: master
  variables:
    stage: unknown
  interceptors:
    preStopSleep:
      enabled: null
      options:
        seconds: 3
    removeResourceSpecs:
      enabled: null
    removeOldJob:
      enabled: null
    waiter:
      enabled: null
    annotater:
      enabled: null
    grafannotator:
      enabled: null
      options:
        targetURL: ""
        username: ""
        password: ""
    injector:
      enabled: null
    ghStatusChecker:
      enabled: null
      options:
        targetUrlRegex: .*
        contextRegex: .*
        initialDelay: 20s
        pullInterval: 10s
        notificationInterval: 3m0s
- name: repo-no-exist
  owner: rebuy-de
  repo: repo-no-exist
  path: k8s/
  ref: master
  variables:
    stage: unknown
  interceptors:
    preStopSleep:
      enabled: null
      options:
        seconds: 3
    removeResourceSpecs:
      enabled: null
    removeOldJob:
      enabled: null
    waiter:
      enabled: null
    annotater:
      enabled: null
    grafannotator:
      enabled: null
      options:
        targetURL: ""
        username: ""
        password: ""
    injector:
      enabled: null
    ghStatusChecker:
      enabled: null
      options:
        targetUrlRegex: .*
        contextRegex: .*
        initialDelay: 20s
        pullInterval: 10s
        notificationInterval: 3m0s
- name: no-files
  owner: rebuy-de
  repo: foobar
  path: does-not-exist/
  ref: master
  variables:
    stage: unknown
  interceptors:
    preStopSleep:
      enabled: null
      options:
        seconds: 3
    removeResourceSpecs:
      enabled: null
    removeOldJob:
      enabled: null
    waiter:
      enabled: null
    annotater:
      enabled: null
    grafannotator:
      enabled: null
      options:
        targetURL: ""
        username: ""
        password: ""
    injector:
      enabled: null
    ghStatusChecker:
      enabled: null
      options:
        targetUrlRegex: .*
        contextRegex: .*
        initialDelay: 20s
        pullInterval: 10s
        notificationInterval: 3m0s
- name: invalid-file
  owner: rebuy-de
  repo: foobar
  path: invalid/
  ref: master
  variables:
    stage: unknown
  interceptors:
    preStopSleep:
      enabled: null
      options:
        seconds: 3
    removeResourceSpecs:
      enabled: null
    removeOldJob:
      enabled: null
    waiter:
      enabled: null
    annotater:
      enabled: null
    grafannotator:
      enabled: null
      options:
        targetURL: ""
        username: ""
        password: ""
    injector:
      enabled: null
    ghStatusChecker:
      enabled: null
      options:
        targetUrlRegex: .*
        contextRegex: .*
        initialDelay: 20s
        pullInterval: 10s
        notificationInterval: 3m0s

