apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset

metadata:
  name: cluster-profile
  namespace: default
  labels:
    team: platform

spec:
  selector:
    matchExpressions:
    - {key: role, operator: In, values: [silo]}
