settings:
  kubeconfig: ~/.kube/kubeconfig.yml
  output: ./output
  sleep: 1s
  retry-sleep: 250ms
  retry-count: 3
  template-values:
    - key: clusterDomain
      value: main.cloud.rebuy.loc
services:
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /dns
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /elasticsearch
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /mongodb
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /ingress-controller
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /graylog
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /solr
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /zookeeper
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /kube-dashboard
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /heapster
  - repo: github.com/rebuy-de/solr-management-silo
    branch: cloud-350
  - repo: github.com/rebuy-de/green-web
    branch: dockerize
  - repo: github.com/rebuy-de/blue-web
  - repo: github.com/rebuy-de/my-web
