settings:
  kubeconfig: ~/config/kubeconfig.yaml
  output: ./output
  sleep: 1s
  skip-shuffle: false
  skip-fetch: false
  skip-deploy: false
  retry-sleep: 250ms
  retry-count: 3
  ignore-deploy-failures: false
  template-values:
    - key: cluster-domain
      value: test.rebuy.de
services:
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /dns
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /elasticsearch
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /mongodb
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /ingress-controller
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /graylog
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /solr
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /zookeeper
  - repo: github.com/rebuy-de/cloud-infrastructure
    path: /kube-dashboard
  - repo: github.com/rebuy-de/solr-management-silo
    path: /kubernetes/manifests
    branch: cloud-350
  - repo: github.com/rebuy-de/green-web
    path: /kubernetes/manifests
    branch: dockerize
  - repo: github.com/rebuy-de/blue-web
    path: /deployment/k8s/manifests
  - repo: github.com/rebuy-de/my-web
    branch: CLOUD-424-dockerize
    path: deployment/k8s/manifests
