settings:
  kubeconfig: test-fixtures/kubeconfig.yml
  output: target/test-output
  sleep: 1s
  retry-sleep: 250ms
  retry-count: 3
  template-values:
    - key: clusterDomain
      value: unit-test.rebuy.de
services:
  - repo: repos/bish
  - repo: repos/bash
    branch: special
  - repo: repos/bosh
    path: //deployment/foo
