defaults:
  owner: rebuy-de
  path: deployment/k8s/
  variables:
    clusterDomain: unit-test.example.org
    secret: foo
  interceptors:
    preStopSleep:
      enabled: true
      options:
        seconds: 3
    waiter:
      enabled: true

services:
- repo: bish
- repo: bash
  variables:
    clusterDomain: test.example.com
- repo: bosh
  path: //deployment/foo
- name: foo
  repo: bar
- owner: kubernetes
  repo: blub
- repo: meh
  path: deployment/k8s
- repo: aka
  name: bim
  alias:
  - baz
- name: guess
  repo: k8s-guess
  path: other
- repo: cloud
  name: cloud
  path: /
