default:
  owner: rebuy-de
  path: deployment/k8s/
  context: abc
  variables:
    clusterDomain: unit-test.example.org
    secret: foo

contexts:
  abc:
    variables:
      bish: bash
  def:
    variables:
      bish: bosh

services:
- repo: bish
- repo: bash
  variables:
    clusterDomain: test.example.com
- repo: bosh
  path: //deployment/foo
- name: foo
  repo: bar
- owner: kubernetes
  repo: blub
- repo: meh
  path: deployment/k8s
