defaults:
  owner: rebuy-de
  path: deployment/k8s/
  context: abc
  variables:
    clusterDomain: unit-test.example.org
    secret: foo
  interceptors:
    preStopSleep:
      enabled: true
      options:
        seconds: 3
    waiter:
      enabled: true

contexts:
  abc:
    variables:
      bish: bash
  def:
    variables:
      bish: bosh
    interceptors:
      removeResourceSpecs:
        enabled: true
      preStopSleep:
        enabled: false

services:
- repo: bish
- repo: bash
  variables:
    clusterDomain: test.example.com
- repo: bosh
  path: //deployment/foo
- name: foo
  repo: bar
- owner: kubernetes
  repo: blub
- repo: meh
  path: deployment/k8s
- repo: aka
  name: bim
  alias:
  - baz
